# Generated by Django 2.2.4 on 2019-11-23 14:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('duty_title', models.CharField(max_length=50, verbose_name='Role Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dead_line', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('responsible', models.ManyToManyField(related_name='assigned_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty',
                'verbose_name_plural': 'Duties',
            },
        ),
    ]
